
language: ruby
rvm:
- 2.1
  
# Containers are cool!  
sudo: false

install: 
- bundle install

script: bundle exec jekyll build
branches:
  only:
  - master

deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  on:
    branch: test
