# Site settings
title: Home for albanian party
email:
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username: AwkwardBen
address:
  - line: London
  - line:
  # Feel free to add more lines here 
telephone: 
copyright:

# API settings
google_api_key: AIzaSyBSO5Fg3P43Jz_tc_kOYGZdN8aWOmqqkFo

# Build settings
markdown: kramdown